services:
  protoc:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace
    working_dir: /workspace
    command: [
      /usr/local/bin/protoc,
      --proto_path=./mobilus_client/proto/,
      --mypy_out=./mobilus_client/proto/,
      # --python_out=./mobilus_client/proto/,
      call_events_request.proto,
      current_state_request.proto,
      current_state_response.proto,
      devices_list_request.proto,
      devices_list_response.proto,
      login_request.proto,
      login_response.proto
    ]
